- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  setPreference: false
  playTimeTracker: AntagSubvertedSilicon
  color: '#c832e6'
  objective: roles-antag-subverted-silicon-objective
