- type: antag
  id: InitialInfected
  name: roles-antag-initial-infected-name
  antagonist: true
  setPreference: true
  playTimeTracker: AntagInitialInfected
  objective: roles-antag-initial-infected-objective
  guides: [ Zombies ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1h

- type: antag
  id: Zombie
  name: roles-antag-zombie-name
  antagonist: true
  setPreference: false
  playTimeTracker: AntagZombie
  objective: roles-antag-zombie-objective
  guides: [ Zombies ]
